[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = ['unreachable', 1878, 2018, 5159, 5574]

# https://github.com/foundry-rs/foundry/issues/7607
# https://github.com/foundry-rs/foundry/pull/7334#issuecomment-1987154623
# https://github.com/foundry-rs/foundry/issues/3097
unchecked_cheatcode_artifacts = true
fs_permissions = [{ access = "read", path = "./"}]
